const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = require('node:path').resolve(__dirname, '..') + '/';
const context = {window:{},document:{querySelector:()=>({})},matchMedia:()=>({matches:false}),URL};
vm.createContext(context);
vm.runInContext(fs.readFileSync(root+'data.js','utf8'),context);
vm.runInContext(fs.readFileSync(root+'project-evidence.js','utf8'),context);
const source=fs.readFileSync(root+'app.js','utf8');
new vm.Script(source);
const helpers=source.slice(0,source.lastIndexOf('  renderNavigation();'))+'window.test={mergeRepositories,matches,safeUrl,escape,validRepositories,revealProgress};})();';
vm.runInContext(helpers,context);
const {mergeRepositories,matches,safeUrl,escape,validRepositories}=context.window.test;
const data=context.window.PORTFOLIO;
const reveal=context.window.test.revealProgress;
assert.equal(reveal(1000,1000),0);
assert.equal(reveal(500,1000),1);
assert.equal(reveal(800,1000),.5);
assert(reveal(850,1000)<reveal(700,1000));
assert.equal(reveal(0,0),1);
for(const file of ['assets/sk-assemble.gif','assets/sk-pixel.png'])assert(fs.existsSync(root+file));
const projects=mergeRepositories(data.repositorySnapshot);
assert.equal(projects[0].name,'NowServing');
assert.equal(projects[1].name,'FitLive');
assert.equal(projects.length,12);
assert.equal(new Set(projects.map(p=>p.id)).size,projects.length);
assert.equal(projects.filter(p=>matches(p,'AWS')).length,1);
assert(projects.filter(p=>matches(p,'Python')).length>1);
assert(projects.every(p=>matches(p,'All')));
assert(projects.filter(p=>matches(p,'Applied AI')).length>=4);
assert.equal(data.location,'Seattle');
assert.equal(data.experience.items[0].role,'Software Engineer - Gen AI');
for(const project of projects)assert(fs.existsSync(root+'assets/diagrams/'+project.id+'.svg'));
assert(!safeUrl('javascript:alert(1)'));
assert(!safeUrl('http://example.com'));
assert(safeUrl('https://github.com/kirann05'));
assert.equal(escape('<script>'),'&lt;script&gt;');
assert(!validRepositories([null]));
assert(!validRepositories([{name:'x',topics:[{}]}]));
assert(validRepositories(data.repositorySnapshot));
const fork={...data.repositorySnapshot[0],name:'unwanted-fork',fork:true};
assert(!mergeRepositories([fork]).some(p=>p.id===fork.name));
for(const file of ['index.html','styles.css','app.js','data.js','favicon.svg','assets/lucide.min.js',data.resume,...data.projects.items.map(p=>p.image).filter(Boolean)]) assert(fs.existsSync(root+file),file);
assert(fs.readFileSync(root+data.resume).subarray(0,5).toString()==='%PDF-');
assert(!/Shiva|Goldman Sachs|Tata Consultancy|Irving/.test(fs.readFileSync(root+'data.js','utf8')));
console.log('PASS: syntax, featured ordering, deduplication, AWS/Python/All filters, fork exclusion, safe URLs, HTML escaping, malformed cache validation, local assets, PDF signature and identity');
